# Generated by Django 5.2.8 on 2025-11-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('numbers', models.CharField(max_length=100)),
                ('bonus_number', models.IntegerField()),
            ],
        ),
    ]
