# Generated by Django 5.2.8 on 2025-11-14 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('draw_date', models.DateField()),
                ('winning_numbers', models.CharField(blank=True, max_length=50)),
                ('bonus_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_drawn', models.BooleanField(default=False)),
                ('total_sales_amount', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50)),
                ('is_auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('prize', models.PositiveBigIntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='LottoResult',
        ),
    ]
